# Generated by Django 2.0.7 on 2018-07-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_roaster_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roaster',
            name='logo_url',
        ),
    ]
