# Generated by Django 2.0.7 on 2018-07-22 18:31

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('coffee', '0003_remove_roaster_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('varietal', models.CharField(max_length=50)),
                ('processing_method', models.CharField(max_length=100)),
                ('roast_level', models.CharField(choices=[('l', 'Light'), ('m', 'Medium'), ('md', 'Medium Dark'), ('d', 'Dark')], help_text='Roast Level', max_length=2)),
                ('roaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Roaster')),
                ('tasting_notes', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
