# Generated by Django 2.0.7 on 2018-07-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_bean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='processing_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bean',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bean',
            name='varietal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
