# Generated by Django 2.0.7 on 2018-08-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
